### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by amuagarwal** [backmeupplz/shieldy#123]
How i restrict bot command to be visible to admin only currently it showing to all the group members.
Or command or way to clear old message history posted in group by Shieldy.

Thanks in advance

**Comment by backmeupplz** [comment]
There is no command to clear old message history posted by Shieldy, delete it manually if you need to. /help command will still be visible in the command dropdown in the chats with Shieldy. You can /lock Shieldy so that only admins can execute commands on it. You can also manually delete configuration messages after you set up Shieldy in your group.
